export const SEND_REQUEST_START = 'SEND_REQUEST_START';
export const SEND_REQUEST_SUCCESS = 'SEND_REQUEST_SUCCESS';
export const SEND_REQUEST_FAIL = 'SEND_REQUEST_FAIL';

export const FETCH_FLEET_START = 'FETCH_FLEET_START';
export const FETCH_FLEET_SUCCESS = 'FETCH_FLEET_SUCCESS';
export const FETCH_FLEET_FAIL = 'FETCH_FLEET_FAIL';

export const FETCH_TEAM_START = 'FETCH_TEAM_START';
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS';
export const FETCH_TEAM_FAIL = 'FETCH_TEAM_FAIL';

export const FETCH_OFFERS_START = 'FETCH_OFFERS_START';
export const FETCH_OFFERS_SUCCESS = 'FETCH_OFFERS_SUCCESS';
export const FETCH_OFFERS_FAIL = 'FETCH_OFFERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const INITIALIZE = 'INITIALIZE';
